### ISSUE TITLE
README examples incomplete

### ISSUE THREAD

**Issue by alexy** [cequence-io/openai-scala-client#7]
If you're a bit rusty with Futures and Akka, it takes some time to dig the ExecutionContext.  Also ModelId is not found, so instead one can just use "text-davinci-003" directly.  Then you have to get the model by doing things like model.value.get.toOption.get to look at it in the real.  It would have to have an example app using the client to run a dialogue in the terminal to show folks how imports are set up to get them up and running.  If someone has an app handy please send as a PR.

**Comment by peterbanda** [comment]
Hi @alexy,

In order to use `ModelId`, which is a convenient but non-exhaustive list of available models, you can do just:

```
import io.cequence.openaiscala.domain.ModelId
```

Not sure what you meant by `model.value.get.toOption.get` but, as you said, it's possible to use `String` instead of `ModelId` and directly type the model name if needed.

Regarding an example app I am planing to provide a seed demo project with similar functionality that you described.

**Comment by hgavert** [comment]
I was not able to find which imports are needed even to get the first 2 lines work. Could you just add the required imports to the readme - examples, please.

**Comment by peterbanda** [comment]
More than 15 examples added to a new project https://github.com/cequence-io/openai-scala-client/tree/master/openai-examples
